<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '¿Estas seguro de que deseas eliminar este item?',
    'Auth Key' => 'Clave de autenticación',
    'Background Img' => 'Imagen de portada',
    'Birthdate' => 'Fecha de nacimiento',
    'Cache' => 'Cache',
    'Country' => 'Pais',
    'Create Movie' => 'Añadir película',
    'Create Tvshow' => 'Añadir serie',
    'Create User' => 'Añadir usuario',
    'Created At' => 'Fecha de creación',
    'Delete' => 'Eliminar',
    'Description' => 'Descripción',
    'Email' => 'Correo Electrónico',
    'Episode Num' => 'Episodio',
    'ID' => 'ID',
    'Id Tmdb' => 'ID TMDb',
    'Last Update' => 'Ultima actualización',
    'Movies' => 'Peliculas',
    'Name' => '',
    'Password' => '',
    'Password Reset Token' => '',
    'Profile Img' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Season Num' => '',
    'State' => '',
    'The requested page does not exist.' => '',
    'Tmdb Gtoken' => '',
    'Tvshow' => '',
    'Tvshows' => '',
    'Update' => '',
    'Update Movie: {nameAttribute}' => '',
    'Update Tvshow: {nameAttribute}' => '',
    'Update User: {nameAttribute}' => '',
    'Username' => '',
    'Users' => '',
];
